theme: jekyll-theme-modernist
# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://amblg.ru
author: Алексей Мельников
email: alsermel@gmail.com
aboutme: Привет. Меня зовут Мельников Алексей. На этом ресурсе собираю знания по тестированию и обеспечению качества. Делаю упор на рассмотрение заявленных тем с точек зрения как можно большего числа авторов
description: "Алексей Мельников. Блог"
keywords: "тестирование программного обеспечение, обеспечение качества, тестирование программ"
google_analytics_key: UA-90371948-1]
favicon:     "/images/favicon.ico"
plugins:
  - jekyll-sitemap
