theme: jekyll-theme-modernist
# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: https://almeln.github.io/ALMELN.ru/
author: Алексей Мельников
description: "Максимум выдержек и ссылок на источники по тестированию и обеспечении качества программного обеспечения"
keywords: "тестирование программного обеспечение, обеспечение качества, тестирование программ"
default_locale: "ru_RU"
plugins:
  - jekyll-sitemap
